Fix logrotate config
Logrotate failed because the config file was not owned by root:

```
error: Ignoring /opt/homebrew/etc/logrotate.conf because the file owner is wrong (should be root or user with uid 0).
```

Now we make sure the file is owned by root.

Also adjusted config to be 500MB max like the other roles. The homebrew
launchd service runs `daily`, the `hourly` setting has no effect here.

Signed-off-by: Arthur Koziel <arthur@arthurkoziel.com>